version: '2'
services:
  sonarqube:
    image: sonarqube
    volumes:
      - data:/opt/sonarqube/data
      - logs:/opt/sonarqube/logs
      - extensions:/opt/sonarqube/extensions
    ports:
      - 9000:9000
volumes:
  data: 
    external: true
  logs:
    external: true
  extensions:
    external: true
